Repository SimpleREST/SimpleStub, pull requests merged in 2022-12, with the labels that each got.

#17 Develop
  .gitignore
  README.md
  boiler/Application.php
  boiler/Stub.php
  composer.json
  config/config.php
  docs/README.en.md
  docs/README.ru.md
  public/composer.json
  public/css/main.css
  public/img/simpleplug-main-bg.jpg
  public/index.php
  public/js/main.js
  resources/values/strings.php
Labels: documentation, enhancement

#20 Develop
  README.md
  docs/README.ru.md
Labels: documentation

#23 Корректировка работы системы
  boiler/Application.php
  boiler/Stub.php
  public/index.php
  public/js/main.js
Labels: bug, enhancement
