Repository SimpleREST/SimpleStub, pull requests merged in 2023-11, with the labels that each got.

#31 Develop
  boiler/app.php
  composer.json
  config/config.php
  docs/README.ru.md
  public/composer.json
  public/index.php
  res/values/Resources.php
  res/values/de/Resources.php
  res/values/en/Resources.php
  res/values/ru/Resources.php
  res/views/README.md
  resources/values/strings.php
Labels: bug, enhancement

#32 Реорганизация скелета приложения
  boiler/app.php
  res/Values/De/Resources.php
  res/Values/En/Resources.php
  res/Values/Resources.php
  res/Values/Ru/Resources.php
  res/Views/README.md
Labels: bug

#35 Develop
  app/Config.php
  boiler/app.php
  composer.json
  docs/README.ru.md
  public/index.php
  res/Values/De/Resources.php
  res/Values/En/Resources.php
  res/Values/Language.php
  res/Values/Resources.php
  res/Values/Ru/Resources.php
Labels: documentation, enhancement

#36 Develop
  boiler/app.php
  composer.json
  docs/README.ru.md
Labels: bug
